import type { Metadata } from 'next'
import { atkinsonMono, atkinsonNext } from './fonts/fonts'
import { ThemeProvider } from 'next-themes'
import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${atkinsonMono.variable} ${atkinsonNext.variable} bg-background dark:bg-background antialiased`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
